batch_size_training: '3'
batching_strategy: packing
checkpoint_type: StateDictType.SHARDED_STATE_DICT
context_length: '4096'
dist_checkpoint_folder: fine-tuned
dist_checkpoint_root_folder: PATH/to/save/FSDP/model
enable_fsdp: 'True'
enable_profiler: 'False'
flop_counter: 'True'
freeze_layers: 'False'
fsdp_activation_checkpointing: 'True'
fsdp_cpu_offload: 'False'
gamma: '0.85'
gradient_accumulation_steps: '1'
gradient_clipping: 'False'
gradient_clipping_threshold: '1.0'
low_cpu_fsdp: 'True'
lr: '0.0001'
max_steps_profiling: '10'
mixed_precision: 'True'
model_name: meta-llama/Llama-2-7b-hf
num_epochs: '1'
num_freeze_layers: '1'
num_workers_dataloader: '1'
one_gpu: 'False'
optimizer: AdamW
output_dir: .
peft_method: lora
profile_output_dir: profile_output
profiler: 'False'
pure_bf16: 'True'
quantization: 'False'
run_validation: 'True'
save_metrics: 'False'
save_model: 'False'
save_optimizer: 'False'
seed: '42'
sharding_strategy: ShardingStrategy.FULL_SHARD
use_fast_kernels: 'False'
use_fp16: 'False'
use_global_loss: 'False'
use_peft: 'False'
val_batch_size: '1'
weight_decay: '0.0'
